CODE_KEY = 'eChat_ForumOhMyGod'

HOST_ADDR_BASE = 'http://127.0.0.1:8088/'


DOMAIN_DICT = {
    'com': '0',
    'cn': '1',
    'net': '2',
    'org': '3',
}

MAIL_HOME_DICT = {
    'gmail': 'a',
    'outlook': 'b',
    'yahoo': 'c',
    'msn': 'd',
    'hotmail': 'e',
    'qq': 'f',
    '163': 'g',
    '126': 'h',
    'sina': 'i',
    'sohu': 'j',
    'sougou': 'k',
}

# 字母数字转译密码本
NAME_ENCODE_DICT = { 
    'a': '2',
    'b': 'd',
    'c': 'E',
    'd': '7',
    'e': 'G',
    'f': 'h',
    'g': 'I',
    'h': 'j',
    'i': 'K',
    'j': 'l',
    'k': 'M',
    'l': 'n',
    'm': 'O',
    'n': 'p',
    'o': 'Q',
    'p': '3',
    'q': 'S',
    'r': 't',
    's': '4',
    't': 'v',
    'u': 'W',
    'v': '1',
    'w': 'Y',
    'x': 'z',
    'y': '0',
    'z': 'b',
    'A': '9',
    'B': 'a',
    'C': 'Z',
    'D': 'y',
    'E': '6',
    'F': 'w',
    'G': 'V',
    'H': 'u',
    'I': 'T',
    'J': 's',
    'K': 'R',
    'L': 'q',
    'M': 'P',
    'N': 'o',
    'O': 'N',
    'P': 'm',
    'Q': 'L',
    'R': 'k',
    'S': 'J',
    'T': 'i',
    'U': '8',
    'V': 'g',
    'W': 'F',
    'X': 'e',
    'Y': 'D',
    'Z': 'c',
    '0': 'B',
    '1': 'H',
    '2': 'f',
    '3': 'X',
    '4': '5',
    '5': 'U',
    '6': 'r',
    '7': 'C',
    '8': 'x',
    '9': 'A',
}